version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: url_inspector_pw
      MYSQL_DATABASE: url_inspector
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_DSN: "root:url_inspector_pw@tcp(mysql:3306)/url_inspector?charset=utf8mb4&parseTime=True&loc=Local"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql-data: