# air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o main ."
  bin = "main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]

[log]
  time = true
